### ISSUE TITLE
cli example broken as of deno 1.0.2

### ISSUE THREAD

**Issue by 1player** [ianfabs/nanoid#8]
```
$ deno -V
deno 1.0.2
$ deno run https://deno.land/x/nanoid/cli.ts
Download https://deno.land/x/nanoid/cli.ts
Download https://deno.land/x/nanoid/mod.ts
Download https://deno.land/x/nanoid/customAlphabet.ts
Download https://deno.land/x/nanoid/url.ts
Download https://deno.land/std/flags/mod.ts
Warning Implicitly using master branch https://deno.land/std/flags/mod.ts
Download https://deno.land/std/testing/asserts.ts
Download https://deno.land/x/nanoid/random.ts
Download https://deno.land/x/nanoid/customRandom.ts
Warning Implicitly using master branch https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/fmt/colors.ts
Download https://deno.land/std/testing/diff.ts
Warning Implicitly using master branch https://deno.land/std/testing/diff.ts
Warning Implicitly using master branch https://deno.land/std/fmt/colors.ts
Compile https://deno.land/x/nanoid/cli.ts
error: TS2739 [ERROR]: Type 'Reader & ReaderSync & Closer & { rid: number; }' is missing the following properties from type 'File': write, writeSync, seek, seekSync
const log = async (message: string, type: Deno.File = Deno.stdin) => {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/nanoid/cli.ts:15:37

TS2345 [ERROR]: Argument of type 'Writer & WriterSync & Closer & { rid: number; }' is not assignable to parameter of type 'Reader'.
  Property 'read' is missing in type 'Writer & WriterSync & Closer & { rid: number; }' but required in type 'Reader'.
  Deno.copy(Deno.stdout, buf);
            ~~~~~~~~~~~
    at https://deno.land/x/nanoid/cli.ts:18:13

    'read' is declared here.
        read(p: Uint8Array): Promise<number | null>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at $asset$/lib.deno.ns.d.ts:219:5

TS2345 [ERROR]: Argument of type 'string | (() => string)' is not assignable to parameter of type 'string'.
  Type '() => string' is not assignable to type 'string'.
  log(id);
      ~~
    at https://deno.land/x/nanoid/cli.ts:48:7

Found 3 errors.
```

**Comment by ianfabs** [comment]
This should be working now. Thank you for your help
